CREATE TABLE IF NOT EXISTS device_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id VARCHAR(100) NOT NULL,
    profile_version INTEGER NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    device_type VARCHAR(50) NOT NULL,
    definition_json TEXT NOT NULL,
    definition_hash VARCHAR(64) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_device_profiles_identity UNIQUE (profile_id, profile_version)
);

ALTER TABLE devices ADD COLUMN IF NOT EXISTS profile_id VARCHAR(100);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS profile_version INTEGER;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS archived_reason VARCHAR(500);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS archived_by VARCHAR(100);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS command_sequence BIGINT NOT NULL DEFAULT 0;

UPDATE devices
SET profile_id = 'legacy-generic-v1',
    profile_version = 1
WHERE profile_id IS NULL OR TRIM(profile_id) = '' OR profile_version IS NULL;

ALTER TABLE devices ALTER COLUMN profile_id SET NOT NULL;
ALTER TABLE devices ALTER COLUMN profile_version SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_devices_profile ON devices (profile_id, profile_version);
CREATE INDEX IF NOT EXISTS idx_devices_archived_at ON devices (archived_at);

ALTER TABLE device_connections ADD COLUMN IF NOT EXISTS profile_version INTEGER;
ALTER TABLE device_connections ADD COLUMN IF NOT EXISTS agent_id VARCHAR(100);
ALTER TABLE device_connections ADD COLUMN IF NOT EXISTS driver_id VARCHAR(100);
ALTER TABLE device_connections ADD COLUMN IF NOT EXISTS last_seen TIMESTAMP;
ALTER TABLE device_connections ADD COLUMN IF NOT EXISTS connected_at TIMESTAMP;
ALTER TABLE device_connections ADD COLUMN IF NOT EXISTS disconnected_at TIMESTAMP;

UPDATE device_connections
SET profile_version = 1
WHERE profile_id IS NOT NULL AND profile_version IS NULL;

CREATE INDEX IF NOT EXISTS idx_device_connections_agent_external
    ON device_connections (agent_id, transport, external_id);
