CREATE TABLE IF NOT EXISTS edge_agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id VARCHAR(100) NOT NULL,
    site_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    version VARCHAR(100),
    status VARCHAR(30) NOT NULL,
    last_seen TIMESTAMP,
    metadata_json TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_edge_agents_agent_id UNIQUE (agent_id),
    CONSTRAINT fk_edge_agents_site FOREIGN KEY (site_id) REFERENCES sites (id)
);

CREATE INDEX IF NOT EXISTS idx_edge_agents_site_status ON edge_agents (site_id, status);

CREATE TABLE IF NOT EXISTS discovered_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id VARCHAR(100) NOT NULL,
    agent_id BIGINT NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    profile_id VARCHAR(100) NOT NULL,
    profile_version INTEGER NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    manufacturer VARCHAR(100),
    model VARCHAR(100),
    endpoint VARCHAR(500),
    status VARCHAR(30) NOT NULL,
    claimed_device_id BIGINT,
    first_seen TIMESTAMP NOT NULL,
    last_seen TIMESTAMP NOT NULL,
    metadata_json TEXT,
    CONSTRAINT uk_discovered_devices_candidate UNIQUE (candidate_id),
    CONSTRAINT uk_discovered_devices_agent_external UNIQUE (agent_id, external_id),
    CONSTRAINT fk_discovered_devices_agent FOREIGN KEY (agent_id) REFERENCES edge_agents (id),
    CONSTRAINT fk_discovered_devices_device FOREIGN KEY (claimed_device_id) REFERENCES devices (id)
);

CREATE INDEX IF NOT EXISTS idx_discovered_devices_status ON discovered_devices (agent_id, status);

CREATE TABLE IF NOT EXISTS device_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(100) NOT NULL,
    site_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    archived_at TIMESTAMP,
    CONSTRAINT uk_device_groups_public_id UNIQUE (public_id),
    CONSTRAINT uk_device_groups_site_name UNIQUE (site_id, name),
    CONSTRAINT fk_device_groups_site FOREIGN KEY (site_id) REFERENCES sites (id)
);

CREATE TABLE IF NOT EXISTS device_group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,
    added_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_device_group_member UNIQUE (group_id, device_id),
    CONSTRAINT fk_device_group_members_group FOREIGN KEY (group_id) REFERENCES device_groups (id),
    CONSTRAINT fk_device_group_members_device FOREIGN KEY (device_id) REFERENCES devices (id)
);

CREATE INDEX IF NOT EXISTS idx_device_group_members_device ON device_group_members (device_id);

CREATE TABLE IF NOT EXISTS command_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id VARCHAR(100) NOT NULL,
    site_id BIGINT NOT NULL,
    group_id BIGINT,
    target_kind VARCHAR(30) NOT NULL,
    target_label VARCHAR(255) NOT NULL,
    type VARCHAR(100) NOT NULL,
    parameters_json TEXT,
    status VARCHAR(50) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    requested_via VARCHAR(100) NOT NULL,
    requested_by VARCHAR(100),
    requested_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    expires_at TIMESTAMP,
    retry_of_batch_id VARCHAR(100),
    total_count INTEGER NOT NULL DEFAULT 0,
    pending_count INTEGER NOT NULL DEFAULT 0,
    sent_count INTEGER NOT NULL DEFAULT 0,
    acknowledged_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    rejected_count INTEGER NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_command_batches_batch_id UNIQUE (batch_id),
    CONSTRAINT uk_command_batches_site_idempotency UNIQUE (site_id, idempotency_key),
    CONSTRAINT fk_command_batches_site FOREIGN KEY (site_id) REFERENCES sites (id),
    CONSTRAINT fk_command_batches_group FOREIGN KEY (group_id) REFERENCES device_groups (id)
);

ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS batch_id VARCHAR(100);
ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS sequence_no BIGINT;
ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS request_fingerprint VARCHAR(64);
ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS request_origin VARCHAR(100);
ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS requested_by VARCHAR(100);
ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS sent_at TIMESTAMP;
ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;
ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP;
ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS failure_code VARCHAR(100);
ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS retry_of_command_id VARCHAR(100);
ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS dispatch_attempts INTEGER NOT NULL DEFAULT 0;

UPDATE device_commands
SET request_origin = COALESCE(request_origin, 'LEGACY'),
    completed_at = CASE WHEN status IN ('ACKNOWLEDGED', 'FAILED') THEN COALESCE(acknowledged_at, requested_at) ELSE NULL END
WHERE request_origin IS NULL OR TRIM(request_origin) = '';

CREATE UNIQUE INDEX IF NOT EXISTS uk_device_commands_batch_device
    ON device_commands (batch_id, device_id);
CREATE INDEX IF NOT EXISTS idx_device_commands_status_requested
    ON device_commands (status, requested_at);
CREATE INDEX IF NOT EXISTS idx_device_commands_batch_status
    ON device_commands (batch_id, status);

CREATE TABLE IF NOT EXISTS command_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_id BIGINT NOT NULL,
    from_status VARCHAR(50),
    to_status VARCHAR(50) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    detail VARCHAR(2000),
    payload_json TEXT,
    occurred_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_command_events_command FOREIGN KEY (command_id) REFERENCES device_commands (id)
);

CREATE INDEX IF NOT EXISTS idx_command_events_command_occurred
    ON command_events (command_id, occurred_at);

CREATE TABLE IF NOT EXISTS device_telemetry_samples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    bucket_start TIMESTAMP NOT NULL,
    sampled_at TIMESTAMP NOT NULL,
    source VARCHAR(100) NOT NULL,
    state_json TEXT NOT NULL,
    CONSTRAINT uk_device_telemetry_bucket UNIQUE (device_id, bucket_start),
    CONSTRAINT fk_device_telemetry_device FOREIGN KEY (device_id) REFERENCES devices (id)
);

CREATE INDEX IF NOT EXISTS idx_device_telemetry_device_sampled
    ON device_telemetry_samples (device_id, sampled_at);

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS status VARCHAR(30);
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS alert_code VARCHAR(100);
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS acknowledged_at TIMESTAMP;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS acknowledged_by VARCHAR(100);

UPDATE alerts SET status = CASE WHEN resolved THEN 'RESOLVED' ELSE 'OPEN' END
WHERE status IS NULL OR TRIM(status) = '';

ALTER TABLE alerts ALTER COLUMN status SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_alerts_status_level_created ON alerts (status, level, created_at);
