-- P0-01: Keycloak subjects are mapped to platform users.  Passwords and
-- refresh tokens deliberately never enter this database; Keycloak owns them.
CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject VARCHAR(255) NOT NULL,
    username VARCHAR(128) NOT NULL,
    display_name VARCHAR(255),
    email VARCHAR(320),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_app_users_subject UNIQUE (subject)
);

CREATE TABLE roles (
    code VARCHAR(32) PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

INSERT INTO roles (code, name)
SELECT 'OWNER', 'Owner'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE code = 'OWNER');

INSERT INTO roles (code, name)
SELECT 'ADMIN', 'Administrator'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE code = 'ADMIN');

INSERT INTO roles (code, name)
SELECT 'OPERATOR', 'Operator'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE code = 'OPERATOR');

INSERT INTO roles (code, name)
SELECT 'VIEWER', 'Viewer'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE code = 'VIEWER');

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_code VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_code),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_code) REFERENCES roles (code)
);

CREATE INDEX idx_app_users_username ON app_users (username);
