-- P0-01: roles come from Keycloak claims; memberships decide which
-- organization/site resources that authenticated user can actually access.
CREATE TABLE organization_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_organization_memberships_user_org UNIQUE (user_id, organization_id),
    CONSTRAINT fk_organization_memberships_user FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT fk_organization_memberships_org FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE site_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    site_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_site_memberships_user_site UNIQUE (user_id, site_id),
    CONSTRAINT fk_site_memberships_user FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT fk_site_memberships_site FOREIGN KEY (site_id) REFERENCES sites (id)
);

CREATE INDEX idx_organization_memberships_user ON organization_memberships (user_id);
CREATE INDEX idx_site_memberships_user ON site_memberships (user_id);
