-- P0-04: edge agents authenticate with an independently rotatable secret.
-- The plaintext secret is returned once by the provisioning API and is never
-- persisted; token_hash stores a BCrypt digest only.
CREATE TABLE agent_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id VARCHAR(100) NOT NULL,
    agent_id BIGINT NOT NULL,
    token_hash VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    last_used_at TIMESTAMP,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_agent_credentials_credential_id UNIQUE (credential_id),
    CONSTRAINT fk_agent_credentials_agent FOREIGN KEY (agent_id) REFERENCES edge_agents (id)
);

CREATE INDEX idx_agent_credentials_agent_status ON agent_credentials (agent_id, status);
CREATE INDEX idx_agent_credentials_status_expires ON agent_credentials (status, expires_at);

-- This audit trail intentionally stores neither a raw token nor a token hash.
CREATE TABLE credential_rotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    previous_credential_id BIGINT,
    replacement_credential_id BIGINT,
    action VARCHAR(30) NOT NULL,
    actor_subject VARCHAR(255),
    reason VARCHAR(1000),
    occurred_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_credential_rotations_agent FOREIGN KEY (agent_id) REFERENCES edge_agents (id),
    CONSTRAINT fk_credential_rotations_previous FOREIGN KEY (previous_credential_id) REFERENCES agent_credentials (id),
    CONSTRAINT fk_credential_rotations_replacement FOREIGN KEY (replacement_credential_id) REFERENCES agent_credentials (id)
);

CREATE INDEX idx_credential_rotations_agent_occurred ON credential_rotations (agent_id, occurred_at);
