-- R1 weather privacy: retain only a purpose/timestamp/outcome audit of an
-- outbound provider call. URLs, exact coordinates, tokens and raw responses
-- are not stored in this table.
CREATE TABLE weather_provider_access_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    provider_code VARCHAR(32) NOT NULL,
    purpose VARCHAR(48) NOT NULL,
    outcome VARCHAR(24) NOT NULL,
    coordinate_precision VARCHAR(16) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_ms BIGINT,
    error_code VARCHAR(64),
    CONSTRAINT fk_weather_provider_access_events_site
        FOREIGN KEY (site_id) REFERENCES sites (id)
);

CREATE INDEX idx_weather_provider_access_site_occurred
    ON weather_provider_access_events (site_id, occurred_at DESC);

-- Existing diagnostic payloads can include the provider's echoed latitude and
-- longitude. Drop them once rather than retaining historical precise data.
UPDATE site_weather_snapshots
SET raw_payload_json = NULL
WHERE raw_payload_json IS NOT NULL;

-- V9/V10 fingerprints previously contained coordinates in clear text. The
-- application now writes a keyed HMAC fingerprint, so old values are removed
-- and refreshed under the new representation instead of retaining precision.
UPDATE site_weather_snapshots
SET configuration_fingerprint = NULL
WHERE configuration_fingerprint IS NOT NULL;

UPDATE site_weather_forecast_points
SET configuration_fingerprint = NULL
WHERE configuration_fingerprint IS NOT NULL;
