CREATE TABLE devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    device_id VARCHAR(64) NOT NULL,
    type VARCHAR(50),
    protocol VARCHAR(50),
    status VARCHAR(20),
    location VARCHAR(255),
    firmware_version VARCHAR(255),
    temperature DOUBLE PRECISION,
    humidity DOUBLE PRECISION,
    cpu_usage DOUBLE PRECISION,
    uptime_seconds BIGINT,
    signal_strength DOUBLE PRECISION,
    last_seen TIMESTAMP,
    registered_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_devices_device_id UNIQUE (device_id)
);

CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT,
    level VARCHAR(20) NOT NULL,
    message VARCHAR(500) NOT NULL,
    resolved BOOLEAN NOT NULL,
    created_at TIMESTAMP,
    resolved_at TIMESTAMP,
    CONSTRAINT fk_alerts_device FOREIGN KEY (device_id) REFERENCES devices (id)
);
