-- P1-RETENTION-01: R1 keeps the hot telemetry table bounded without forcing
-- an irreversible partitioning strategy.  All timestamps added here are UTC
-- aware.  Existing no-zone rows are intentionally left null/legacy so the
-- retention worker cannot silently guess their time basis.

CREATE TABLE IF NOT EXISTS device_telemetry_samples_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_sample_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,
    bucket_start TIMESTAMP NOT NULL,
    sampled_at TIMESTAMP NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE,
    observed_at TIMESTAMP WITH TIME ZONE,
    observed_time_trust VARCHAR(32),
    bucket_start_utc TIMESTAMP WITH TIME ZONE,
    source VARCHAR(100) NOT NULL,
    state_json VARCHAR(32600) NOT NULL,
    archived_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_telemetry_archive_source_sample UNIQUE (source_sample_id)
);

CREATE INDEX IF NOT EXISTS idx_telemetry_archive_device_received
    ON device_telemetry_samples_archive (device_id, received_at);
CREATE INDEX IF NOT EXISTS idx_telemetry_archive_received
    ON device_telemetry_samples_archive (received_at);

CREATE TABLE IF NOT EXISTS retention_holds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type VARCHAR(40) NOT NULL,
    scope_id VARCHAR(255) NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE,
    reason VARCHAR(1000) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    released_by VARCHAR(255),
    released_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_retention_holds_active
    ON retention_holds (scope_type, scope_id, starts_at, ends_at, released_at);

CREATE TABLE IF NOT EXISTS retention_hold_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hold_id BIGINT NOT NULL,
    action VARCHAR(32) NOT NULL,
    actor_subject VARCHAR(255) NOT NULL,
    detail VARCHAR(1000),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_retention_hold_events_hold FOREIGN KEY (hold_id) REFERENCES retention_holds (id)
);

CREATE INDEX IF NOT EXISTS idx_retention_hold_events_hold_occurred
    ON retention_hold_events (hold_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS retention_job_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(100) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    dry_run BOOLEAN NOT NULL,
    data_category VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    window_start TIMESTAMP WITH TIME ZONE,
    window_end TIMESTAMP WITH TIME ZONE,
    estimated_rows BIGINT NOT NULL,
    archived_rows BIGINT NOT NULL,
    deleted_rows BIGINT NOT NULL,
    held_rows BIGINT NOT NULL,
    failed_rows BIGINT NOT NULL,
    watermark TIMESTAMP WITH TIME ZONE,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    failure_reason VARCHAR(2000),
    correlation_id VARCHAR(100),
    CONSTRAINT uk_retention_job_runs_run_category UNIQUE (run_id, data_category)
);

CREATE INDEX IF NOT EXISTS idx_retention_job_runs_category_started
    ON retention_job_runs (data_category, started_at DESC);

-- New audit/command writes dual-write these fields.  They are deliberately
-- nullable so N-1 remains compatible and unprovable legacy rows stay out of
-- automatic deletion until a separately reviewed reconciliation completes.
ALTER TABLE activity_events ADD COLUMN IF NOT EXISTS occurred_at_utc TIMESTAMP WITH TIME ZONE;
ALTER TABLE command_events ADD COLUMN IF NOT EXISTS occurred_at_utc TIMESTAMP WITH TIME ZONE;
ALTER TABLE credential_rotations ADD COLUMN IF NOT EXISTS occurred_at_utc TIMESTAMP WITH TIME ZONE;
ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS requested_at_utc TIMESTAMP WITH TIME ZONE;
ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS sent_at_utc TIMESTAMP WITH TIME ZONE;
ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS completed_at_utc TIMESTAMP WITH TIME ZONE;
ALTER TABLE device_commands ADD COLUMN IF NOT EXISTS expires_at_utc TIMESTAMP WITH TIME ZONE;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS created_at_utc TIMESTAMP WITH TIME ZONE;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS resolved_at_utc TIMESTAMP WITH TIME ZONE;

CREATE INDEX IF NOT EXISTS idx_activity_events_occurred_utc ON activity_events (occurred_at_utc);
CREATE INDEX IF NOT EXISTS idx_command_events_occurred_utc ON command_events (occurred_at_utc);
CREATE INDEX IF NOT EXISTS idx_credential_rotations_occurred_utc ON credential_rotations (occurred_at_utc);
CREATE INDEX IF NOT EXISTS idx_device_commands_requested_utc ON device_commands (requested_at_utc);
CREATE INDEX IF NOT EXISTS idx_alerts_resolved_utc ON alerts (resolved, resolved_at_utc);
