CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_organizations_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_sites_organization_code UNIQUE (organization_id, code),
    CONSTRAINT fk_sites_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS spaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    parent_id BIGINT,
    name VARCHAR(255) NOT NULL,
    path VARCHAR(512) NOT NULL,
    CONSTRAINT uk_spaces_site_path UNIQUE (site_id, path),
    CONSTRAINT fk_spaces_site FOREIGN KEY (site_id) REFERENCES sites (id),
    CONSTRAINT fk_spaces_parent FOREIGN KEY (parent_id) REFERENCES spaces (id)
);

ALTER TABLE devices ADD COLUMN IF NOT EXISTS public_id VARCHAR(100);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS site_id BIGINT;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS space_id BIGINT;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS reported_state_json VARCHAR(4000);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS desired_state_json VARCHAR(4000);

UPDATE devices
SET public_id = CONCAT('device-', RANDOM_UUID())
WHERE public_id IS NULL OR public_id = '';

UPDATE devices
SET status = 'OFFLINE'
WHERE status IS NULL;

UPDATE devices
SET temperature = COALESCE(temperature, 0),
    humidity = COALESCE(humidity, 0),
    cpu_usage = COALESCE(cpu_usage, 0),
    uptime_seconds = COALESCE(uptime_seconds, 0),
    signal_strength = COALESCE(signal_strength, 0)
WHERE temperature IS NULL
   OR humidity IS NULL
   OR cpu_usage IS NULL
   OR uptime_seconds IS NULL
   OR signal_strength IS NULL;

UPDATE devices
SET reported_state_json = '{}'
WHERE reported_state_json IS NULL;

UPDATE devices
SET desired_state_json = '{}'
WHERE desired_state_json IS NULL;

ALTER TABLE devices ALTER COLUMN public_id SET NOT NULL;
ALTER TABLE devices ALTER COLUMN public_id SET DEFAULT CONCAT('device-', RANDOM_UUID());
ALTER TABLE devices ALTER COLUMN status SET NOT NULL;
ALTER TABLE devices ALTER COLUMN status SET DEFAULT 'OFFLINE';
ALTER TABLE devices ALTER COLUMN temperature SET NOT NULL;
ALTER TABLE devices ALTER COLUMN temperature SET DEFAULT 0;
ALTER TABLE devices ALTER COLUMN humidity SET NOT NULL;
ALTER TABLE devices ALTER COLUMN humidity SET DEFAULT 0;
ALTER TABLE devices ALTER COLUMN cpu_usage SET NOT NULL;
ALTER TABLE devices ALTER COLUMN cpu_usage SET DEFAULT 0;
ALTER TABLE devices ALTER COLUMN uptime_seconds SET NOT NULL;
ALTER TABLE devices ALTER COLUMN uptime_seconds SET DEFAULT 0;
ALTER TABLE devices ALTER COLUMN signal_strength SET NOT NULL;
ALTER TABLE devices ALTER COLUMN signal_strength SET DEFAULT 0;
ALTER TABLE devices ALTER COLUMN reported_state_json SET NOT NULL;
ALTER TABLE devices ALTER COLUMN reported_state_json SET DEFAULT '{}';
ALTER TABLE devices ALTER COLUMN desired_state_json SET NOT NULL;
ALTER TABLE devices ALTER COLUMN desired_state_json SET DEFAULT '{}';

ALTER TABLE devices ADD CONSTRAINT IF NOT EXISTS fk_devices_organization
    FOREIGN KEY (organization_id) REFERENCES organizations (id);
ALTER TABLE devices ADD CONSTRAINT IF NOT EXISTS fk_devices_site
    FOREIGN KEY (site_id) REFERENCES sites (id);
ALTER TABLE devices ADD CONSTRAINT IF NOT EXISTS fk_devices_space
    FOREIGN KEY (space_id) REFERENCES spaces (id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_devices_public_id ON devices (public_id);
CREATE INDEX IF NOT EXISTS idx_devices_organization_site ON devices (organization_id, site_id);
CREATE INDEX IF NOT EXISTS idx_devices_site_space ON devices (site_id, space_id);

CREATE TABLE IF NOT EXISTS device_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    transport VARCHAR(50) NOT NULL,
    profile_id VARCHAR(100),
    external_id VARCHAR(255),
    status VARCHAR(50),
    metadata_json VARCHAR(4000),
    CONSTRAINT fk_device_connections_device FOREIGN KEY (device_id) REFERENCES devices (id)
);

CREATE INDEX IF NOT EXISTS idx_device_connections_device ON device_connections (device_id);

CREATE TABLE IF NOT EXISTS device_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_id VARCHAR(100) NOT NULL,
    device_id BIGINT NOT NULL,
    type VARCHAR(100) NOT NULL,
    parameters_json VARCHAR(4000),
    idempotency_key VARCHAR(128),
    status VARCHAR(50),
    error_message VARCHAR(2000),
    requested_at TIMESTAMP,
    acknowledged_at TIMESTAMP,
    CONSTRAINT uk_device_commands_command_id UNIQUE (command_id),
    CONSTRAINT fk_device_commands_device FOREIGN KEY (device_id) REFERENCES devices (id)
);

CREATE INDEX IF NOT EXISTS idx_device_commands_device_requested_at ON device_commands (device_id, requested_at);
CREATE INDEX IF NOT EXISTS idx_device_commands_device_idempotency ON device_commands (device_id, idempotency_key);

CREATE TABLE IF NOT EXISTS activity_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    detail VARCHAR(2000),
    payload_json VARCHAR(4000),
    occurred_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_activity_events_device FOREIGN KEY (device_id) REFERENCES devices (id)
);

CREATE INDEX IF NOT EXISTS idx_activity_events_device_occurred_at ON activity_events (device_id, occurred_at);
