CREATE TABLE IF NOT EXISTS site_weather_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    timezone VARCHAR(64),
    manual_elevation_m DOUBLE PRECISION,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    provider_code VARCHAR(32) NOT NULL DEFAULT 'OPEN_METEO',
    condensation_temperature_device_id BIGINT,
    condensation_temperature_field VARCHAR(128),
    CONSTRAINT uk_site_weather_settings_site UNIQUE (site_id),
    CONSTRAINT fk_site_weather_settings_site FOREIGN KEY (site_id) REFERENCES sites (id),
    CONSTRAINT fk_site_weather_settings_temperature_device
        FOREIGN KEY (condensation_temperature_device_id) REFERENCES devices (id)
);

CREATE TABLE IF NOT EXISTS site_weather_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    provider_code VARCHAR(32) NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    weather_code INTEGER,
    condition_text VARCHAR(64),
    temperature_c DOUBLE PRECISION,
    apparent_temperature_c DOUBLE PRECISION,
    relative_humidity_pct INTEGER,
    surface_pressure_hpa DOUBLE PRECISION,
    wind_speed_kmh DOUBLE PRECISION,
    wind_direction_deg INTEGER,
    elevation_m DOUBLE PRECISION,
    raw_payload_json CLOB,
    CONSTRAINT fk_site_weather_snapshots_site FOREIGN KEY (site_id) REFERENCES sites (id)
);

CREATE INDEX IF NOT EXISTS idx_site_weather_snapshots_site_fetched
    ON site_weather_snapshots (site_id, fetched_at DESC);

CREATE TABLE IF NOT EXISTS site_weather_forecast_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    forecast_kind VARCHAR(16) NOT NULL,
    forecast_at TIMESTAMP WITH TIME ZONE NOT NULL,
    weather_code INTEGER,
    temperature_c DOUBLE PRECISION,
    temperature_max_c DOUBLE PRECISION,
    temperature_min_c DOUBLE PRECISION,
    precipitation_probability_pct INTEGER,
    wind_speed_kmh DOUBLE PRECISION,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_site_weather_forecast_points_site FOREIGN KEY (site_id) REFERENCES sites (id)
);

CREATE INDEX IF NOT EXISTS idx_site_weather_forecast_site_kind_at
    ON site_weather_forecast_points (site_id, forecast_kind, forecast_at);

INSERT INTO site_weather_settings (
    site_id, latitude, longitude, timezone, manual_elevation_m, enabled, provider_code
)
SELECT site.id, 22.5431, 114.0579, 'Asia/Shanghai', 32, TRUE, 'OPEN_METEO'
FROM sites site
JOIN organizations organization ON organization.id = site.organization_id
WHERE organization.code = 'demo-org'
  AND site.code = 'demo-site'
  AND NOT EXISTS (
      SELECT 1 FROM site_weather_settings setting WHERE setting.site_id = site.id
  );
