server:
  port: 8080

spring:
  application:
    name: iot-manager

  profiles:
    default: dev

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
