spring:
  datasource:
    url: jdbc:h2:mem:iot-manager-test-${random.uuid};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: false

iot:
  security:
    enabled: false
  web:
    allowed-origins:
      - "*"
  command-simulator:
    enabled: false

  simulator:
    enabled: false

  weather:
    scheduler-enabled: false
